# Change these first
owner: dmpstr # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Monofile
    url: https://excited-beaded-wrist.glitch.me/
  - name: Website
    url: https://dmpstr.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.dmpstr.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "The status thingy idk"
  introMessage: "Idk man"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
